// <auto-generated />
using Index_Libri.Server.BLL.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Index_Libri.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Book", b =>
                {
                    b.Property<string>("ISBN")
                        .HasColumnType("text");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BookListId")
                        .HasColumnType("integer");

                    b.Property<int>("Pages")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.HasKey("ISBN");

                    b.HasIndex("BookListId");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("BookList", b =>
                {
                    b.Property<int>("BookListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BookListId"));

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BookListId");

                    b.HasIndex("UserEmail")
                        .IsUnique();

                    b.ToTable("BookList");
                });

            modelBuilder.Entity("Index_Libri.Server.BLL.Model.ApplicationUser", b =>
                {
                    b.Property<string>("UserEmail")
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.HasKey("UserEmail");

                    b.ToTable("ApplicationUser");
                });

            modelBuilder.Entity("Book", b =>
                {
                    b.HasOne("BookList", "BookList")
                        .WithMany("Books")
                        .HasForeignKey("BookListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookList");
                });

            modelBuilder.Entity("BookList", b =>
                {
                    b.HasOne("Index_Libri.Server.BLL.Model.ApplicationUser", "ApplicationUser")
                        .WithOne("BookList")
                        .HasForeignKey("BookList", "UserEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("BookList", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Index_Libri.Server.BLL.Model.ApplicationUser", b =>
                {
                    b.Navigation("BookList")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
